[package]
name = "join_lecture"
version = "0.1.0"
authors = ["Daksh <dak-x@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[examples]

[dependencies]
structopt = "*"
json = "*"
chrono = "0.4"
